language: cpp
sudo: required

matrix:
  include:
    - compiler: gcc
      env: BUILD=gcc
#    - compiler: clang
#      env: BUILD=clang
#    - compiler: clang
#      env: BUILD=analyze

install:
  - sh platform/linux/travis-install.sh

script:
  - sh platform/linux/travis-build.sh
